### ISSUE TITLE
bip85-cli bip39 command line issues

### ISSUE THREAD

**Issue by kirillkovalenko** [ethankosakovsky/bip85#6]
Environment:

Windows Server 2016 
Python: Python 3.7.8 (tags/v3.7.8:4b47a5b6ba, Jun 28 2020, 08:53:46) [MSC v.1916 64 bit (AMD64)] on win32
bip85: 7892bbddc51f498d1a693cca3f6d642b75cb3373 

## num-words parameter does not work

```
❯ bip85-cli.exe --xprv [removed] --index 1 bip39 --num-words 24
usage: bip85-cli bip39 [-h]
                       [--language {english,japanese,korean,spanish,chinese_simplified,chinese_traditional,french,italian,czech}]
                       [--num-words {12,15,18,21,24}]
bip85-cli bip39: error: argument --num-words: invalid choice: '24' (choose from 12, 15, 18, 21, 24)
```
none of the values (12, 15, 18, 21, 24) work

## language czech crashes

```
❯ bip85-cli.exe --xprv [removed] ErRHyVk8 --index 1 bip39 --language czech
Using master private key: [removed]
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Scripts\bip85-cli-script.py", line 11, in <module>
    load_entry_point('bip85==0.2.0', 'console_scripts', 'bip85-cli')()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\bip85-0.2.0-py3.7.egg\bip85\cli.py", line 64, in main
    print(app.bip39(xprv, args.language, args.num_words, args.index))
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\bip85-0.2.0-py3.7.egg\bip85\app.py", line 45, in bip39
    return bip85.entropy_to_bip39(entropy, words, language)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\bip85-0.2.0-py3.7.egg\bip85\bip85.py", line 92, in entropy_to_bip39
    m = bip39(language)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\mnemonic-0.19-py3.7.egg\mnemonic\mnemonic.py", line 72, in __init__
    "%s/%s.txt" % (self._get_directory(), language), "r", encoding="utf-8"
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python37_64\\lib\\site-packages\\mnemonic-0.19-py3.7.egg\\mnemonic\\wordlist/czech.txt'
```

**Comment by ethankosakovsky** [comment]
Should have been fixed in #11
